fix category filter
SmithVyne/react-bookstore pull request #4
Opened 2020-12-14 11:57 UTC by SmithVyne

I implemented all the features of this project according to the [instructions here](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376030/)

2020-12-14 12:24 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Nice work on this PR. Let's fix some things before merging.
Check my comments for suggestions.
- [x] add a title to this PR.


### Martin Afani

2020-12-14 12:24 UTC, whiz25 commented on src/reducers/filter.js
> +const filterReducer = (state = '', action) => {
- assign the category `All` as default. `const filterReducer = (state = 'All', action)`

2020-12-14 12:24 UTC, whiz25 commented on src/components/CategoryFilter.js
> +);
- merge the category `All` with available categories.
```javascript
const filterCategories = [...['All']...Categories]
filterCategories.map((category){})
```

2020-12-15 01:29 UTC, Torres-ssf approved these changes
### PR Approved
Hi @SmithVyne :hand: 
Awesome job implementing the requested changes.
You may merge the PR
Good luck with the next milestone

Happy coding :computer: 
**Sergio Torres**

2020-12-15 01:37 UTC, merged